apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-credentials
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "creds1"
          objectType: "secretsmanager"